/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Terrier_PrunningDaatCuda */

#ifndef _Included_Terrier_PrunningDaatCuda
#define _Included_Terrier_PrunningDaatCuda
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Terrier_PrunningDaatCuda
 * Method:    prunningParallel
 * Signature: (IDJDDIIIDIIID)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_Terrier_PrunningDaatCuda_prunningParallel
  (JNIEnv *, jobject, jint, jdouble, jlong, jdouble, jdouble, jint, jint, jint, jdouble, jint, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
